---
title: "Netflix Viewing History"
author: "Patrick Meyer"
date: "7 2 2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## My Netflix Viewing History

This is a short presentation of my Netflix viewing habits from 03/2017 to 02/2021.

Some of the ideas were inspired by
https://towardsdatascience.com/explore-your-activity-on-netflix-with-r-how-to-analyze-and-visualize-your-viewing-history-e85792410706

```{r data import, echo = FALSE, message=FALSE, warning=FALSE}

library(stringr)
library(aweek)
library(plotly)
library(tidyr)
library(dplyr)

#Import data
netflix = read.csv("NetflixViewingHistory.csv", sep = ";")

#Add zeros because stupid excel screwed up the dates
netflix$Date = as.character(netflix$Date)
netflix$Date = sapply(netflix$Date, FUN = 
                        function(x){if(nchar(x) < 6){x = paste("0", x, sep = "")}
                                      else{x = x}})

#Break the title into 3 seperate columns with "Title of show", "Season", "Title of episode"
netflix = separate(netflix, col = Title, into = c("Title", "Season", "Episode"), sep = ': ')

#Exclude rows which are not in the proper format and are therefore likely now series
netflix = netflix[-which(is.na(netflix$Episode)),]

#Break up the Date-Column in separate columns
netflix$days = substr(netflix$Date, start = 1, stop = 2)
netflix$months = substr(netflix$Date, start = 3, stop = 4)
netflix$years = paste("20", substr(netflix$Date, start = 5, stop = 6), sep = "")
netflix$Date = as.Date(paste(netflix$years, "-", netflix$months, "-", netflix$days, sep = ""))
netflix$week = date2week(netflix$Date)
netflix$week = substr(netflix$week, start = 7, stop = 8)
netflix$weekYear = paste(netflix$years, netflix$week, sep = "-")
#Order by Date
netflix = netflix[order(netflix$Date),]
```

## Plot of My 10 Most Watched Shows Since 03/2017

```{r plot1, warning=FALSE}
#Extract a data frame in which each Title from the base data frame is counted
netflixTitleCounts = count(netflix, Title)
netflixTitleCounts= netflixTitleCounts[order(netflixTitleCounts$n, decreasing = TRUE),]

#Turn the title into a factor with defined order, so plot_ly can recognize this order instead of sorting alphabetically
netflixTitleCounts$Title = factor(netflixTitleCounts$Title, levels = netflixTitleCounts$Title[order(netflixTitleCounts$n, decreasing = FALSE)])

#Plot the ten most watched shows
topten = plot_ly(data = netflixTitleCounts[1:10,], x = ~n, y = ~Title, type = "bar", 
            orientation = "h", marker = list(color = "rgba(229,9,20,1)")) %>%
  layout(yaxis = list(title = list(standoff = 1), color = "white"), 
         xaxis = list(color = "white", title = "Total Number of Views"),
         title = list(text = "My 10 Most Watched Shows on Netflix Since 03/2017", font = list(color = "white")),
         margin = list(t = 50),
         plot_bgcolor = "rgba(0,0,0,1)", 
         paper_bgcolor = "rgba(0,0,0,1)")

topten
```

## Views per Day Over the Years

You can zoom in to get a closer look at monthly/weekly/daily information. :)


```{r plot2}
dailyEpisodes = count(netflix, Date)
viewsPerDay = plot_ly(data = dailyEpisodes, x = ~Date, y = ~n, type = "bar", 
                      marker = list(color = "rgba(229,9,20,1)"))  %>%
    layout(yaxis = list(color = "white", title = "Views per Day"), 
         xaxis = list(color = "white", title = "Date"),
         title = list(text = "My Views Per Day on Netflix Since 03/2017", font = list(color = "white")),
         plot_bgcolor = "rgba(0,0,0,1)", 
         paper_bgcolor = "rgba(0,0,0,1)")
viewsPerDay
```
